drop table if exists player CASCADE 
drop table if exists team CASCADE 
create table player (player_id bigint generated by default as identity, player_name varchar(255), age integer not null, team_team_id bigint, primary key (player_id))
create table team (team_id bigint generated by default as identity, team_name varchar(255), primary key (team_id))
alter table player add constraint FKkswv8pkevhfnyhkxgwxdfbkvc foreign key (team_team_id) references team ON DELETE CASCADE